version: '3.7'
services:
    nginx:
        build:
            context: ./dev
            dockerfile: nginx.docker
        volumes:
            - ../:/app
        depends_on:
            - php-fpm
        ports:
            - "8080:80"

    php-fpm:
        build:
            context: ./dev
            dockerfile: php-fpm.docker
        volumes:
            - ../:/app

